**lab 1**

1.   **Describe Numpy and list the various features of numpy . build a program to display all arithematic options using numpy arrays**



2.   **What is pandas ? Write a programm to craete dataframe and access the data in a dataframe ?**



In [ ]:
print("Welcome to machine Learning lab 1".center(10,'-'))

Welcome to machine Learning lab 1


In [ ]:
import numpy as np

In [ ]:
my_list = [1,2,3]
arr1 : np.ndarray = np.array(my_list,dtype=np.int64)
print(arr1)

[1 2 3]


In [ ]:
# Printing the Shape of the array
arr1.shape

(3,)

In [ ]:
my_list_2d : list[int] = [[1,2,3],[4,5,6]]
arr2 : np.ndarray = np.array(my_list_2d)

In [ ]:
#finding the value at 2,3 from index
arr2[1,2]

6

In [ ]:
# printing a coloum value 2 nd coloum
arr2[:,1]

array([2, 5])

In [ ]:
# applying a operation on each numpy array

no = input("Addition of a numerical value to given default to 5")
print(no)
if(no == ""):
  no = 5
arr1 + no

Addition of a numerical value to given default to 5



array([6, 7, 8])

In [ ]:
no = input("Subtraction of a numerical value to given default to 5")
print(no)
if(no == ""):
  no = 5
arr1 -  no

Subtraction of a numerical value to given default to 5



array([-4, -3, -2])

In [ ]:
no = input("Multiplication of a numerical value to given default to 5")
print(no)
if(no == ""):
  no = 5
arr1 *  no

Multiplication of a numerical value to given default to 5



array([ 5, 10, 15])

In [ ]:
no = input("Division of a numerical value to given default to 5")
print(no)
if(no == ""):
  no = 5
arr1 /  no

Division of a numerical value to given default to 5



array([0.2, 0.4, 0.6])

In [ ]:
print("Doing the exponentioal of an array")
print(arr1)
np.exp(arr1)

Doing the exponentioal of an array
[1 2 3]


array([ 2.71828183,  7.3890561 , 20.08553692])

In [ ]:
#any other function like 4 th roots
ok = int(input("Please enter ower that needs to be considered"))
if(ok == ""):
  ok = 3
np.power(arr1,ok)

Please enter ower that needs to be considered5


array([  1,  32, 243])

In [ ]:
arr1

array([ 15,  60, 135])

In [ ]:
# working ith multiple arrays
arr1 : np.ndarray = np.array([1,2,3])
arr2 : np.ndarray = np.array([4,5,6])

In [ ]:
print("addition of array1 and array2",np.add(arr1,arr2))
print("subtraction of array1 and array2",np.subtract(arr1,arr2))
print("Multiplication of array1 and array2",np.multiply(arr1,arr2))
print("dicision of array1 and array2",np.divide(arr1,arr2))

addition of array1 and array2 [5 7 9]
subtraction of array1 and array2 [-3 -3 -3]
Multiplication of array1 and array2 [ 4 10 18]
dicision of array1 and array2 [0.25 0.4  0.5 ]


In [ ]:
print("Min of array",arr1.min())
print("Max of array",arr1.max())
print("sum of array",arr1.sum())
print("Mean of array",arr1.mean())
print("Variance of array",arr1.var())

Min of array 1
Max of array 3
sum of array 6
Mean of array 2.0
Variance of array 0.6666666666666666


**Pandas **

In [ ]:
import pandas as pd

array1 = ["a","b","c"]
series1 = pd.Series(array1)
series1

0    a
1    b
2    c
dtype: object

In [ ]:

array_2 = np.array([[1,2,3],[4,5,6]])
row_names = ['a','b']
coloum_names = ['one','two','three']
df = pd.DataFrame(array_2,index=row_names,columns=coloum_names)
df

one  two  three
a    1    2      3
b    4    5      6

In [ ]:
# prima indian diabeties dataset
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/diabetes.csv")
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

import numpy as np
from google.colab import autoviz
df_1077518402196590466 = autoviz.get_df('df_1077518402196590466')

def value_plot(df, y, sort_ascending=False, figsize=(2, 1)):
  from matplotlib import pyplot as plt
  if sort_ascending:
    df = df.sort_values(y).reset_index(drop=True)
  _, ax = plt.subplots(figsize=figsize)
  df[y].plot(kind='line')
  plt.title(y)
  ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(df_1077518402196590466, *['Pregnancies'], **{})
chart

import numpy as np
from google.colab import autoviz
df_1077518402196590466 = autoviz.get_df('df_1077518402196590466')

def value_plot(df, y, sort_ascending=False, figsize=(2, 1)):
  from matplotlib import pyplot as plt
  if sort_ascending:
    df = df.sort_values(y).reset_index(drop=True)
  _, ax = plt.subplots(figsize=figsize)
  df[y].plot(kind='line')
  plt.title(y)
  ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(df_1077518402196590466, *['Glucose'], **{})
chart

import numpy as np
from google.colab import autoviz
df_1077518402196590466 = autoviz.get_df('df_1077518402196590466')

def value_plot(df, y, sort_ascending=False, figsize=(2, 1)):
  from matplotlib import pyplot as plt
  if sort_ascending:
    df = df.sort_values(y).reset_index(drop=True)
  _, ax = plt.subplots(figsize=figsize)
  df[y].plot(kind='line')
  plt.title(y)
  ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(df_1077518402196590466, *['BloodPressure'], **{})
chart

import numpy as np
from google.colab import autoviz
df_1077518402196590466 = autoviz.get_df('df_1077518402196590466')

def value_plot(df, y, sort_ascending=False, figsize=(2, 1)):
  from matplotlib import pyplot as plt
  if sort_ascending:
    df = df.sort_values(y).reset_index(drop=True)
  _, ax = plt.subplots(figsize=figsize)
  df[y].plot(kind='line')
  plt.title(y)
  ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(df_1077518402196590466, *['SkinThickness'], **{})
chart

import numpy as np
from google.colab import autoviz
df_1077518402196590466 = autoviz.get_df('df_1077518402196590466')

def histogram(df, colname, num_bins=20, figsize=(2, 1)):
  from matplotlib import pyplot as plt
  _, ax = plt.subplots(figsize=figsize)
  plt.hist(df[colname], bins=num_bins, histtype='stepfilled')
  plt.ylabel('count')
  plt.title(colname)
  ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(df_1077518402196590466, *['Pregnancies'], **{})
chart

import numpy as np
from google.colab import autoviz
df_1077518402196590466 = autoviz.get_df('df_1077518402196590466')

def histogram(df, colname, num_bins=20, figsize=(2, 1)):
  from matplotlib import pyplot as plt
  _, ax = plt.subplots(figsize=figsize)
  plt.hist(df[colname], bins=num_bins, histtype='stepfilled')
  plt.ylabel('count')
  plt.title(colname)
  ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(df_1077518402196590466, *['Glucose'], **{})
chart

import numpy as np
from google.colab import autoviz
df_1077518402196590466 = autoviz.get_df('df_1077518402196590466')

def histogram(df, colname, num_bins=20, figsize=(2, 1)):
  from matplotlib import pyplot as plt
  _, ax = plt.subplots(figsize=figsize)
  plt.hist(df[colname], bins=num_bins, histtype='stepfilled')
  plt.ylabel('count')
  plt.title(colname)
  ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(df_1077518402196590466, *['BloodPressure'], **{})
chart

import numpy as np
from google.colab import autoviz
df_1077518402196590466 = autoviz.get_df('df_1077518402196590466')

def histogram(df, colname, num_bins=20, figsize=(2, 1)):
  from matplotlib import pyplot as plt
  _, ax = plt.subplots(figsize=figsize)
  plt.hist(df[colname], bins=num_bins, histtype='stepfilled')
  plt.ylabel('count')
  plt.title(colname)
  ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(df_1077518402196590466, *['SkinThickness'], **{})
chart

import numpy as np
from google.colab import autoviz
df_1077518402196590466 = autoviz.get_df('df_1077518402196590466')

def scatter_plots(df, colname_pairs, scatter_plot_size=2.5, size=8, alpha=.6):
  from matplotlib import pyplot as plt
  plt.figure(figsize=(len(colname_pairs) * scatter_plot_size, scatter_plot_size))
  for plot_i, (x_colname, y_colname) in enumerate(colname_pairs, start=1):
    ax = plt.subplot(1, len(colname_pairs), plot_i)
    ax.scatter(df[x_colname], df[y_colname], s=size, alpha=alpha)
    plt.xlabel(x_colname)
    plt.ylabel(y_colname)
    ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = scatter_plots(df_1077518402196590466, *[[['Pregnancies', 'Glucose'], ['Glucose', 'BloodPressure'], ['BloodPressure', 'SkinThickness'], ['SkinThickness', 'Insulin']]], **{})
chart